In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
## sentance 

sent =[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am good developer',
    'understand the meaning of words',
    'your video are good'
]

In [19]:
# check the sentances 
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am good developer',
 'understand the meaning of words',
 'your video are good']

In [20]:
# Define the vocabulary size
voc_size=10000

In [21]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[8803, 7179, 2613, 9961],
 [8803, 7179, 2613, 4973],
 [8803, 3727, 2613, 2938],
 [8659, 8949, 3154, 7621, 7835],
 [8659, 8949, 7621, 208],
 [7809, 8803, 3128, 2613, 7935],
 [1613, 3519, 2293, 7621]]

In [22]:
for words in sent:
    print(words)

the glass of milk
the glass of juice
the cup of tea
I am a good boy
I am good developer
understand the meaning of words
your video are good


In [23]:
## word Embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [25]:
### for make whole sentance in the equal length
sent_length=8
Embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(Embedded_docs)

[[   0    0    0    0 8803 7179 2613 9961]
 [   0    0    0    0 8803 7179 2613 4973]
 [   0    0    0    0 8803 3727 2613 2938]
 [   0    0    0 8659 8949 3154 7621 7835]
 [   0    0    0    0 8659 8949 7621  208]
 [   0    0    0 7809 8803 3128 2613 7935]
 [   0    0    0    0 1613 3519 2293 7621]]


In [26]:
### for ]feature representation need to create 10 demention for compare
dim=10

In [27]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [28]:
### check the model summary 
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [38]:
model.predict(Embedded_docs[[0]][[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[[ 0.02867338, -0.03853043,  0.04470306, -0.04620041,
          0.03661932, -0.02162383, -0.00710173, -0.01931409,
          0.01491893, -0.02820603],
        [ 0.02867338, -0.03853043,  0.04470306, -0.04620041,
          0.03661932, -0.02162383, -0.00710173, -0.01931409,
          0.01491893, -0.02820603],
        [ 0.02867338, -0.03853043,  0.04470306, -0.04620041,
          0.03661932, -0.02162383, -0.00710173, -0.01931409,
          0.01491893, -0.02820603],
        [ 0.02867338, -0.03853043,  0.04470306, -0.04620041,
          0.03661932, -0.02162383, -0.00710173, -0.01931409,
          0.01491893, -0.02820603],
        [-0.03971829,  0.04869946,  0.01541376,  0.01099831,
         -0.04201317,  0.02100632, -0.0413642 ,  0.01478146,
          0.01003547, -0.03057002],
        [-0.02020254, -0.00653629, -0.01693752,  0.012566  ,
          0.02400139,  0.0181529 ,  0.04173617,  0.0360877 ,
         -0.0355952 , -0.0058312 ],
        [-0.02590506, -0.00222998, -0.04699188,  0.0

In [30]:
Embedded_docs[0]

array([   0,    0,    0,    0, 8803, 7179, 2613, 9961])